name: Build
on:
  push:
	branches: [main]
  pull_request:
	branches: [main]
  workflow_dispatch:
env:
  BUILD_TYPE: ${{ fromJSON('["dev", "release"]')[startsWith(github.ref, 'refs/tags/v')] }}
  CORE_LOVE_PACKAGE_PATH: ./core.love
  CORE_LOVE_ARTIFACT_NAME: poyoGame
  PRODUCT_NAME: VSPoyo
  BUNDLE_ID: com.saxashitter.ufpatrf
jobs :
  build-core:
    runs-on: ubuntu-latest
    env:
      OUTPUT_FOLDER: ./build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build core love package
        uses: love-actions/love-actions-core@v1
        with:
          package-path: ${{ env.CORE_LOVE_PACKAGE_PATH }}
      - name: Upload core love package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.CORE_LOVE_ARTIFACT_NAME }}
          path: ${{ env.CORE_LOVE_PACKAGE_PATH }}
  build:
    runs-on: ubuntu-latest
    needs: [build-core]
    steps:
    - uses: actions/checkout@v3
    - uses: nhartland/love-build@master
      id: love-build
      with:
        app_name: 'VS_POYO'
        love_version: '11.4'
    - uses: actions/upload-artifact@v1
      with:
        name: macos-build
        path: ${{ steps.love-build.outputs.macos-filename }}
    - uses: actions/upload-artifact@v1
      with:
       name: win32-build
       path: ${{ steps.love-build.outputs.win32-filename }}
    - uses: actions/upload-artifact@v1
      with:
       name: win64-build
       path: ${{ steps.love-build.outputs.win64-filename }}
    - uses: actions/upload-artifact@v1
      with:
       name: love-build
       path: ${{ steps.love-build.outputs.love-filename }}
  build-android:
    runs-on: ubuntu-latest
    needs: [build-core]
    env:
      OUTPUT_FOLDER: ./build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # Download your core love package here
      - name: Download core love package
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.CORE_LOVE_ARTIFACT_NAME }}
      - name: Make folders
        shell: bash
        run: |
          mkdir -p ./libAndroid/armeabi-v7a/
          mkdir -p ./libAndroid/arm64-v8a/
      - name: Build Android packages
        id: build-packages
        uses: love-actions/love-actions-android@v1
        with:
          app-name: ${{ env.PRODUCT_NAME }}
          bundle-id: ${{ env.BUNDLE_ID }}
          love-package: ${{ env.CORE_LOVE_PACKAGE_PATH }}
          resource-path: ./.github/build/android/${{ env.BUILD_TYPE }}/res
          extra-assets: ./libAndroid/
          product-name: ${{ env.PRODUCT_NAME }}
          version-string: "1.0.0"
          version-code: 100
          output-folder: ${{ env.OUTPUT_FOLDER }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ needs.get-info.outputs.base-name }}_Android_release
          path: ${{ env.OUTPUT_FOLDER }}
